version: '3.8'

# More info at https://containrrr.dev/watchtower

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_LABEL_ENABLE: 'false'
      WATCHTOWER_ROLLING_RESTART: 'true'
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: '<INSERT EMAIL ADDRESS>'
      WATCHTOWER_NOTIFICATION_EMAIL_TO: '<INSERT EMAIL ADDRESS>'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: 'smtp.gmail.com'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: '<INSERT EMAIL ADDRESS>'
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: '<INSERT EMAIL ADDRESS PASSWORD>' 
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: '10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
